_commit: v2.1.0
_src_path: https://github.com/quokkify/project-toolkit.git
components:
-   path: .
    type: node
docker: false
project_name: renovate-presets
release_please: true
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
- default
- javascript
- github-actions
toolkit_version: v2.1.0
