_commit: v3.0.3
_src_path: https://github.com/quokkify/ci-kit.git
allure_report: false
codeql: true
codeql_languages: []
components: []
docker: false
gitleaks: true
project_name: renovate-presets
release_mode: single
release_please: true
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
  - default
  - github-actions
toolkit_version: v3.0.3
