_commit: e19aecb1e0ea318485847b31039cdefb3586321b
_src_path: https://github.com/quokkify/project-toolkit.git
components: []
docker: false
project_name: renovate-presets
release_please: true
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
- default
- github-actions
toolkit_version: v2.1.0
