name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:

  node-1:
    uses: quokkify/project-toolkit/.github/workflows/node-ci.yml@v2.1.0
    with:
      working-directory: "."
      install-command: echo "No Node.js package dependencies in this preset repository"
      run-lint: false
      run-tests: false
      run-build: false


