name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: quokkify/project-toolkit/.github/workflows/release-please.yml@204b0f332c03d8ea8ceed920e3dc7487a13bb224 # v2.12.4
    with:
      mode: single
      release-type: simple
