name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: quokkify/project-toolkit/.github/workflows/release-please.yml@734fd9281ffa353e37c768f7bb56bbcd28347916 # v2.10.1
    with:
      mode: single
      release-type: simple
